### ISSUE TITLE
Property "debug.hwui.renderer" value should be "skiavk" in the script

### ISSUE THREAD

**Issue by LiBoHanse** [tryigit/EnableVulkan#1]
Tested on my android 13 device, changing value from "vulkan" to "skiavk" works(su -c dumpsys gfxinfo com.android.systemui | grep Pipeline returns "Skia (Vulkan)").
"debug.hwui.renderer" with value of "vulkan" should be of something pre android 9 era.

**Comment by tryigit** [comment]
Submit a pull request (you will do it and credit) or close the issue (I will do it).
