### ISSUE TITLE
Wrong name: ACTIONS.SH doesn't make the button appear

### ISSUE THREAD

**Issue by DaveRamirezCodes** [tryigit/EnableVulkan#2]
As per the title the file name is wrong... To make the ACTION button appear in magisk the correct file name should be ACTION.SH and not ACTIONS.SH (with the final S the name is wrong and magisk's webui button not appear)

**Comment by tryigit** [comment]
https://github.com/tryigit/EnableVulkan/releases/tag/V1.2.1
